app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include(('bases.urls','bases'), namespace='bases')),
    path('inv/',include(('inv.urls','inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    
    path('admin/', admin.site.urls),
]

bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from bases.views import Home, HomeSinPrivilegios

urlpatterns = [
    path('',Home.as_view(), name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='bases/login.html'),
        name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='bases/login.html'),
    name='logout'),

    path('sin_privilegios/',HomeSinPrivilegios.as_view(),
    name='sin_privilegios')
    
]

bases/models.py
from django.db import models

from django.contrib.auth.models import User


class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)  
    #  fecha crea
    fc = models.DateTimeField(auto_now_add=True)
    # fecha modifica
    fm = models.DateTimeField(auto_now=True)
    # usuario crea
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    # usuaro modifica
    um = models.IntegerField(blank=True,null=True)

    class Meta:
        abstract = True

bases/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.views import generic

class SinPrivilegios(LoginRequiredMixin, PermissionRequiredMixin):
    raise_exception = False
    redirect_field_name = "redirect_to"

    def handle_no_permission(self):
        from django.contrib.auth.models import AnonymousUser
        if not self.request.user==AnonymousUser():
            self.login_url='bases:sin_privilegios'
        return HttpResponseRedirect(reverse_lazy(self.login_url))

class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'bases/home.html'
    login_url = 'bases:login'

class HomeSinPrivilegios(generic.TemplateView):
    template_name = "bases/sin_privilegios.html"

bases/templates/bases/home.html
{% extends 'base/base.html' %}

bases/templates/bases/login.html
{% extends 'base/base.html' %}

{% block side_bar %}{% endblock %}
{% block top_bar %}{% endblock %}
{% block page_content %}{% endblock %}
{% block footer %}{% endblock %}
{% block login %}

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Bienvenido</h1>
                    <small class="text-danger">
                        {% if form.errors %}
                          {% for field in form %}
                            {% if field.errors %}
                              {% for error in field.errors %}
                                {{ error|escape }}
                              {% endfor %}
                            {% endif %}
                          {% endfor %}
                        
                          {% if form.non_field_errors %}
                            {% for errors in form.non_field_errors %}
                              {{ errors|escape }}
                            {% endfor %}
                          {% endif %}
                        {% endif %}
                    </small>
                  </div>
                  <form class="user" method="POST">
                      {% csrf_token %}
                  <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="id_username" name="username" aria-describedby="emailHelp" placeholder="Ususario">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="id_password" name="password" placeholder="Contraseña">
                    </div>

                    {#{ form.as_p }#}

                    <button type="submit" class="btn btn-primary btn-user btn block">Acceder</button>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

{% endblock %}

{% block js_page %} 

<script>
  {% if form.errors %}
    {% for field in form %}
      {% if field.errors %}
        {% for error in field.errors %}     
          mensaje('{{ error|escape }}', 'red');
        {% endfor %}
      {% endif %}
    {% endfor %}

    {% if form.non_field_errors %}
      {% for errors in form.non_field_errors %}
        mensaje('{{ error|escape }}', 'red');
      {% endfor %}
    {% endif %}
  {% endif %}
</script>

{% endblock %}

bases/templates/bases/sin_privilegios.html
{% extends 'base/base.html' %}
{% block page_content %}
    <div class="col-xl-6 col-md-6 mb-6">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters aling-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Usuario:<mark>{{ user.username }} {{ user.get_full_name }}</mark>
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <mark>No tiene suficientes privilegios</mark>
                            <br>
                            <small>Para poder acceder, debes loguearte con un usuario con privilegios necesarios</small>

                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <a href="{% url 'bases:home' %}" class="btn btn-success"><span class="fa fa-home">Ir al inicio</span>Ir </a>
                                <a href="{% url 'bases:login' %}" class="btn btn-success"><span class="fa fa-user">Ingresar con otro ususario</span>Ir </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}