app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include(('bases.urls','bases'), namespace='bases')),
    path('inv/',include(('inv.urls','inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    
    path('admin/', admin.site.urls),
]

inv/urls.py
from django.urls import path

from .views import CategoriaView, CategoriaNew,CategoriaEdit, \
    CategoriaDel, \
        SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
            MarcaView, MarcaNew, MarcaEdit, MarcaDel, marca_inactiva, \
                UMView, UMNew, UMEdit, UMDel, um_inactiva, \
                    ProductoView, ProductoNew, ProductoEdit, producto_inactivar
                

urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new/', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>/', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>/', CategoriaDel.as_view(), name='categoria_del'),

    path('subcategoria/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategoria/new/', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategoria/edit/<int:pk>/', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>/', SubCategoriaDel.as_view(), name='subcategoria_del'),

    path('marca/', MarcaView.as_view(), name='marca_list'),
    path('marca/new/', MarcaNew.as_view(), name='marca_new'),
    path('marca/edit/<int:pk>/', MarcaEdit.as_view(), name='marca_edit'),
    path('marca/delete/<int:pk>/', MarcaDel.as_view(), name='marca_del'),
    path('marca/inactiva/<int:id>/', marca_inactiva, name='marca_inactiva'),

    path('um/', UMView.as_view(), name='um_list'),
    path('um/new/', UMNew.as_view(), name='um_new'),
    path('um/edit/<int:pk>/', UMEdit.as_view(), name='um_edit'),
    path('um/delete/<int:pk>/', UMDel.as_view(), name='um_del'),
    path('um/inactiva/<int:id>/', um_inactiva, name='um_inactiva'),

    path('productos/', ProductoView.as_view(), name='producto_list'),
    path('productos/new/', ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>/', ProductoEdit.as_view(), name='producto_edit'),
    path('productos/inactiva/<int:id>/', producto_inactivar, name='producto_inactiva'),
]

inv/models.py
from django.db import models

from bases.models import ClaseModelo

class Categoria(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la categoria',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = 'Categorias'   
        
    
class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la categoria',
        unique=True
    )

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion,self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        verbose_name_plural = 'Sub Categorias'
        unique_together = ('categoria', 'descripcion')

class Marca(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la marca',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()

    class Meta:
        verbose_name_plural = 'Marcas' 

class UnidadMedida(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la unidad',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):        
        self.descripcion = self.descripcion.upper()
        super().save()

    class Meta:
        verbose_name_plural = "Unidades de medida"

class Producto(ClaseModelo):
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barra = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencias = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)

    marca = models.ForeignKey(Marca, on_delete = models.CASCADE)
    unidad_medida = models.ForeignKey(UnidadMedida, on_delete = models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete= models.CASCADE)

    def __str___(self):
        return '{}'.format(self.descripcion)
        
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name_plural = "Productos"
        unique_together = ('codigo', 'codigo_barra')

inv/forms.py
from django import forms

from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto


class CategoriaForms(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['descripcion', 'estado']
        labels = {'descripcion':"Descripcion de la Categoria",
                "estado":"Estado"}
        widget = {'descripcion': forms.TextInput}

    def __int__(self, *args, **kwargs):
        super().__int__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class SubCategoriaForms(forms.ModelForm):
    categoria = forms.ModelChoiceField(
        queryset = Categoria.objects.filter(estado=True)
        .order_by('descripcion')
    )
    class Meta:
        model = SubCategoria
        fields = ['categoria', 'descripcion', 'estado']
        labels = {'descripcion':"SubCategoria",
                "estado":"Estado"}
        widget = {'descripcion': forms.TextInput}

    def __int__(self, *args, **kwargs):
        super().__int__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['categoria'].empty_label = "Seleccione la categoria"
        
class MarcaForms(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ['descripcion', 'estado']
        labels = {'descripcion':"Descripcion de la marca",
                "estado":"Estado"}
        widget = {'descripcion': forms.TextInput}

    def __int__(self, *args, **kwargs):
        super().__int__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class UMForms(forms.ModelForm):
    class Meta:
        model = UnidadMedida
        fields = ['descripcion', 'estado']
        labels = {'descripcion':"Descripcion de medida",
                "estado":"Estado"}
        widget = {'descripcion': forms.TextInput}

    def __int__(self, *args, **kwargs):
        super().__int__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class ProductoForms(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['codigo', 'codigo_barra', 'descripcion', 'estado', \
                'precio', 'existencias', 'ultima_compra', 
                'marca',  'subcategoria', 'unidad_medida']
    
        exclude = ['um', 'fm', 'uc', 'fc']
        widget = {'descripcion': forms.TextInput()}

    def __int__(self, *args, **kwargs):
        super().__int__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['ultima_compra'].widget.attrs['readonly'] = True
        self.fields['existencia'].widget.attrs['readonly'] = True

inv/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required


from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto
from .forms import CategoriaForms,SubCategoriaForms, MarcaForms, UMForms, ProductoForms
from bases.views import SinPrivilegios


class CategoriaView(SinPrivilegios, \
     generic.ListView):
    permission_required = "inv.view_categoria"
    model = Categoria
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class CategoriaNew(SuccessMessageMixin,SinPrivilegios, \
    generic.ListView):
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForms
    success_url = reverse_lazy("inv:categoria_list")
    success_message= "Categoria creada satisfactoriamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class CategoriaEdit(SuccessMessageMixin,LoginRequiredMixin,generic.ListView):
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForms
    success_url = reverse_lazy("inv:categoria_list")
    login_url = 'bases:login'
    success_message= "Categoria actualizada satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class CategoriaDel(SuccessMessageMixin,LoginRequiredMixin,generic.ListView):
    model = Categoria
    template_name = 'inv/catalogo_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy("inv:categoria_list")
    success_message= "Categoria borrada satisfactoriamente"

class SubCategoriaView(SuccessMessageMixin, SinPrivilegios, \
     generic.ListView):
    permission_required = "inv.view_subcategoria"
    model = SubCategoria
    template_name = "inv/subcategoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class SubCategoriaNew(LoginRequiredMixin, generic.CreateView):
    model = SubCategoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForms
    success_url = reverse_lazy("inv:subcategoria_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class SubCategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model = SubCategoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForms
    success_url = reverse_lazy("inv:subcategoria_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class SubCategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model = SubCategoria
    template_name = 'inv/catalogo_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy("inv:subcategoria_list")

class MarcaView(SuccessMessageMixin, SinPrivilegios, \
     generic.ListView):
    permission_required = "inv.view_marca"
    model = Marca
    template_name = "inv/marca_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class MarcaNew(LoginRequiredMixin, generic.CreateView):
    model = Marca
    template_name = "inv/marca_form.html"
    context_object_name = "obj"
    form_class = MarcaForms
    success_url = reverse_lazy("inv:marca_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class MarcaEdit(LoginRequiredMixin, generic.UpdateView):
    model = Marca
    template_name = "inv/marca_form.html"
    context_object_name = "obj"
    form_class = MarcaForms
    success_url = reverse_lazy("inv:marca_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class MarcaDel(LoginRequiredMixin, generic.DeleteView):
    model = Marca
    template_name = 'inv/marca_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy("inv:marca_list")

@login_required(login_url='/login/')
@permission_required('inv.change_marca', login_url='bases:sin_privilegios')
def marca_inactiva(request, id):
    marca = Marca.objects.filter(pk = id).first()
    contexto = {}
    template_name = "inv/catalogo_del.html"

    if not marca:
        return redirect("inv:marca_list")

    if request.method == 'GET':
        contexto = {'obj':marca}

    if request.method == 'POST':
        marca.estado=False
        marca.save()
        messages.success(request, 'Marca inactivada')
        return redirect("inv:marca_list")


    return render(request, template_name, contexto)

class UMView(LoginRequiredMixin, generic.ListView):
    model = UnidadMedida
    template_name = "inv/um_list.html"
    context_object_name = "obj"
    login_url = "bases:login"

class UMNew(LoginRequiredMixin, generic.CreateView):
    model = UnidadMedida
    template_name = "inv/um_form.html"
    context_object_name = 'obj'
    form_class = UMForms
    success_url = reverse_lazy("inv:um_list")
    login_url = 'bases:login'

    def form_valid(self, form):        
        form.instance.uc = self.request.user        
        return super().form_valid(form)

class UMDel(LoginRequiredMixin, generic.DeleteView):
    model = UnidadMedida
    template_name = 'inv/catalogo_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy("inv:um_list")
class UMEdit (LoginRequiredMixin, generic.UpdateView):
    model = UnidadMedida
    template_name = "inv/um_form.html"
    form_class = UMForms
    success_url = reverse_lazy("inv:um_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id        
        return super().form_valid(form)

def um_inactiva(request, id):
    um = UnidadMedida.objects.filter(pk = id).first()
    contexto = {}
    template_name = "inv/catalogo_del.html"

    if not um:
        return redirect("inv:um_list")

    if request.method == 'GET':
        contexto = {'obj':um}

    if request.method == 'POST':
        um.estado=False
        um.save()
        return redirect("inv:um_list")

    return render(request, template_name, contexto)

class ProductoView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = "inv/producto_list"
    context_object_name = "obj"
    login_url = "bases:login"

class ProductoNew(LoginRequiredMixin, generic.CreateView):
    model = Producto
    template_name = "inv/producto_form.html"
    context_object_name = 'obj'
    form_class = ProductoForms
    success_url = reverse_lazy("inv:producto_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.uc= self.request.user
        print(self.request.user.id)
        return super().form_valid(form)

class ProductoEdit (LoginRequiredMixin, generic.UpdateView):
    model = Producto
    template_name = "inv/producto_form.html"
    form_class = ProductoForms
    success_url = reverse_lazy("inv:producto_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.uc = self.request.user.id
        print(self.request.user.id)
        return super().form_valid(form)

def producto_inactivar(request, id):
    prod = Producto.objects.filter(pk = id).first()
    contexto = {}
    template_name = "inv/catalogo_del.html"

    if not prod:
        return redirect("inv:producto_list")

    if request.method == 'GET':
        contexto = {'obj':prod}

    if request.method == 'POST':
        prod.estado=False
        prod.save()
        return redirect("inv:producto_list")

    return render(request, template_name, contexto)

inv/templates/inv/categoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de categorias</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones:</div>
          <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
        <div class="alert alert-info"> No hay categoria</div>
        {% else %}
        <table class="table table-striped table-hove">
          <thead>
              <th>Id</th>
              <th>Descripcion</th>
              <th>Estado</th>
              <th>F. Creado</th>
              <th>F. Modif.</th>
              <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ item.id }}</td>
                  <td>{{ item.descripcion }}</td>
                  <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                  <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                  <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                  <td>
                      <a href="{% url 'inv:categoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                      <a href="{% url 'inv:categoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                  </td>
              </tr>
              {% endfor %}
          </tbody>
        </table>
      {% endif %}
    </div>
  </div>

{% endblock %}

{% block js_page %}
<script>
  // call the database jquery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

inv/templates/inv/marca_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de marcas</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones:</div>
          <a class="dropdown-item" href="{% url 'inv:marca_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
        <div class="alert alert-info"> No hay marcas</div>
        {% else %}
        <table class="table table-striped table-hove">
          <thead>
            <th>Id</th>
            <th>Descripcion</th>
            <th>Estado</th>
            <th>F. Creado</th>
            <th>F. Modif.</th>
            <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.descripcion }}</td>
                <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                <td>
                      <a href="{% url 'inv:marca_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                      <a href="{% url 'inv:marca_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                      <a href="{% url 'inv:marca_inactiva' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                  </td>
              </tr>
              {% endfor %}
          </tbody>
        </table>
      {% endif %}
    </div>
  </div>

{% endblock %}

{% block js_page %}
<script>
  // call the database jquery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

inv/templates/inv/producto_list.html
{% extends 'base/base.html' %}

{% block page_content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de Productos</h6>
            <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" onclick="return abrir_modal('{% url 'inv:producto_new' %}')" href="#"><i class="far fa-calendar-plus"></i> Nuevo</a>
            </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
                <div class="alert alert-info">No hay Productos</div>
            {% endif %}

            <table class="table table-striped table-hover">
                <thead>
                    <th>Sub.Cat.</th>
                    <th>Código</th>
                    <th>Barra</th>
                    <th>Descripción</th>
                    <th>Existencia</th>
                    <th>Marca</th>
                    <th>U.M</th>
                    <th>Estado</th>
                    <th class="all">Acciones</th>
                </thead>
                <tbody>
                    {% for item in obj %}
                        <tr>
                            <td>{{ item.subcategoria }}</td>
                            <td>{{ item.codigo }}</td>
                            <td>{{ item.codigo_barra }}</td>
                            <td>{{ item.descripcion }}</td>
                            <td>{{ item.existencia }}</td>
                            <td>{{ item.marca }}</td>
                            <td>{{ item.unidad_medida }}</td>
                            <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                            <td>
                                <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'inv:producto_edit' item.id %}')"><i class="far fa-edit"></i></button>
                                <a href="{% url 'inv:producto_inactiva' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
           
        </div>
    </div>
    
{% endblock %}

{% block js_page%}
<script>
    //llamamos los datatables del plugin del Jquery
    $(document).ready(function(){
        $('.table').DataTable({
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "<span class='fa fa-angle-double-left'></span>",
                    "sLast": "<span class='fa fa-angle-double-right'></span>",
                    "sNext": "<span class='fa fa-angle-right'></span>",
                    "sPrevious": "<span class='fa fa-angle-left'></span>"
                },
                "oAria":{
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
    });
</script>
{% endblock %}

inv/templates/inv/um_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de unidades de medida</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones:</div>
          <a class="dropdown-item" href="{% url 'inv:um_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
        <div class="alert alert-info"> No hay unidades de medida</div>
        {% else %}
        <table class="table table-striped table-hove">
          <thead>
              <th>Id</th>
              <th>Descripcion</th>
              <th>Estado</th>
              <th>F. Creado</th>
              <th>F. Modif.</th>
              <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ item.id }}</td>
                  <td>{{ item.descripcion }}</td>
                  <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                  <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                  <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                  <td>
                      <a href="{% url 'inv:um_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                      <a href="{% url 'inv:um_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                      <a href="{% url 'inv:um_inactiva' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                  </td>
              </tr>
              {% endfor %}
          </tbody>
        </table>
      {% endif %}
    </div>
  </div>

{% endblock %}

{% block js_page %}
<script>
  // call the database jquery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}